#target density scaling factor, default is 1
/pradsim/det/target/densityratio 0

#target material 'hydrogen' for gas hydrogen (default), 'LH2' for liquid hydrogen
/pradsim/det/target/material Ta

#half length of the target cell, in mm
/pradsim/det/target/halfl 0.0 mm

#gun tyle, DON'T change it for beam-on-target simulation
/pradsim/gun/type point

#starting position of the beam, DON'T change it for beam-on-target simulation
/pradsim/gun/pos 0 0 -4800 mm

/pradsim/gun/type file
/pradsim/gun/evtype trident
/pradsim/gun/path md5_4pt4_1000.dat

#frequency of printing out current event number
/pradsim/event/printmodulo 100000

#turn it on for beam-on-target simulation, only record event if there is at least a hit on detector
/pradsim/event/onlyrecordhits true

/pradsim/det/sensitive/virtual true

/run/initialize

# the amount of event we want to run
# /run/beamOn 9960000
/run/beamOn 1000000
